export const SET_BILLING_CYCLE = "SET_BILLING_CYCLE";
export const SET_SELECTED_GROWTH_PLAN = "SET_SELECTED_GROWTH_PLAN";
export const LOAD_PLAN_DATA = "LOAD_PLAN_DATA";
export const CHANGE_ACTIVE_PLAN_VARIATION = "CHANGE_ACTIVE_PLAN_VARIATION";
